;VARACTER GENERATER FOR PC-8001 CRAZY-FIRE
; SPACE
"     "
"     "
"     "
"     "
"     "
"     "
"     "
; !
"  0  "
"  0  "
"  0  "
"  0  "
"  0  "
"     "
"  0  "
; "
" 0 0 "
" 0 0 "
"     "
"     "
"     "
"     "
"     "
; #
" 0 0 "
"00000"
" 0 0 "
" 0 0 "
" 0 0 "
"00000"
" 0 0 "
; $
"  0  "
" 0000"
"0 0  "
" 000 "
"  0 0"
"0000 "
"  0  "
; %
"00   "
"00  0"
"   0 "
"  0  "
" 0   "
"0  00"
"   00"
; &
" 0   "
"0 0  "
"0 0  "
" 0  0"
"0 0 0"
"0  0 "
" 00 0"
; '
" 00  "
"  0  "
" 0   "
"     "
"     "
"     "
"     "
; (
"   0 "
"  0  "
" 0   "
" 0   "
" 0   "
"  0  "
"   0 "
; )
" 0   "
"  0  "
"   0 "
"   0 "
"   0 "
"  0  "
" 0   "
; *
"     "
"  0  "
"0 0 0"
" 000 "
"0 0 0"
"  0  "
"     "
; +
"     "
"  0  "
"  0  "
"00000"
"  0  "
"  0  "
"     "
; ,
"     "
"     "
"     "
"     "
" 00  "
"  0  "
" 0   "
; -
"     "
"     "
"     "
"00000"
"     "
"     "
"     "
; .
"     "
"     "
"     "
"     "
"     "
" 00  "
" 00  "
; /
"     "
"    0"
"   0 "
"  0  "
" 0   "
"0    "
"     "
; 0
" 000 "
"0   0"
"0   0"
"0   0"
"0   0"
"0   0"
" 000 "
; 1
"  0  "
" 00  "
"  0  "
"  0  "
"  0  "
"  0  "
" 000 "
; 2
" 000 "
"0   0"
"    0"
"   0 "
"  0  "
" 0   "
"00000"
; 3
" 000 "
"0   0"
"    0"
"  00 "
"    0"
"0   0"
" 000 "
; 4
"   0 "
"  00 "
" 0 0 "
"0  0 "
"00000"
"   0 "
"   0 "
; 5
"00000"
"0    "
"0    "
"0000 "
"    0"
"    0"
"0000 "
; 6
"  00 "
" 0   "
"0    "
"0000 "
"0   0"
"0   0"
" 000 "
; 7
"00000"
"0   0"
"   0 "
"  0  "
"  0  "
"  0  "
"  0  "
; 8
" 000 "
"0   0"
"0   0"
" 000 "
"0   0"
"0   0"
" 000 "
; 9
" 000 "
"0   0"
"0   0"
" 0000"
"    0"
"   0 "
" 00  "
; :
"     "
" 00  "
" 00  "
"     "
" 00  "
" 00  "
"     "
; ;
"     "
" 00  "
" 00  "
"     "
" 00  "
"  0  "
" 0   "
; <
"   00"
"  0  "
" 0   "
"0    "
" 0   "
"  0  "
"   00"
; =
"     "
"     "
"00000"
"     "
"00000"
"     "
"     "
; >
"00   "
"  0  "
"   0 "
"    0"
"   0 "
"  0  "
"00   "
; ?
" 000 "
"0   0"
"   0 "
"  0  "
"  0  "
"     "
"  0  "

;
;
; @
" 000 "
"0   0"
"0  00"
"0 0 0"
"0 00 "
"0    "
" 0000"
; A
"  0  "
" 0 0 "
"0   0"
"0   0"
"00000"
"0   0"
"0   0"
; B
"0000 "
" 0  0"
" 0  0"
" 000 "
" 0  0"
" 0  0"
"0000 "
; C
" 000 "
"0   0"
"0    "
"0    "
"0    "
"0   0"
" 000 "
; D
"0000 "
" 0  0"
" 0  0"
" 0  0"
" 0  0"
" 0  0"
"0000 "
; E
"00000"
" 0  0"
" 0   "
" 000 "
" 0   "
" 0  0"
"00000"
; F
"00000"
" 0  0"
" 0   "
" 000 "
" 0   "
" 0   "
"000  "
; G
" 0000"
"0    "
"0    "
"0  00"
"0   0"
"0   0"
" 000 "
; H
"0   0"
"0   0"
"0   0"
"00000"
"0   0"
"0   0"
"0   0"
; I
" 000 "
"  0  "
"  0  "
"  0  "
"  0  "
"  0  "
" 000 "
; J
"  000"
"   0 "
"   0 "
"   0 "
"   0 "
"0  0 "
" 00  "
; K
"0   0"
"0  0 "
"0 0  "
"00   "
"0 0  "
"0  0 "
"0   0"
; L
"0    "
"0    "
"0    "
"0    "
"0    "
"0   0"
"00000"
; M
"0   0"
"00 00"
"0 0 0"
"0 0 0"
"0   0"
"0   0"
"0   0"
; N
"0   0"
"0   0"
"00  0"
"0 0 0"
"0  00"
"0   0"
"0   0"
; O
" 000 "
"0   0"
"0   0"
"0   0"
"0   0"
"0   0"
" 000 "
; P
"0000 "
" 0  0"
" 0  0"
" 000 "
" 0   "
" 0   "
" 0   "
; Q
" 000 "
"0   0"
"0   0"
"0   0"
"0 0 0"
"0  0 "
" 00 0"
; R
"0000 "
" 0  0"
" 0  0"
" 000 "
" 00  "
" 0 0 "
" 0  0"
; S
" 000 "
"0   0"
"0    "
" 000 "
"    0"
"0   0"
" 000 "
; T
"00000"
"0 0 0"
"  0  "
"  0  "
"  0  "
"  0  "
" 000 "
; U
"0   0"
"0   0"
"0   0"
"0   0"
"0   0"
"0   0"
" 000 "
; V
"0   0"
"0   0"
"0   0"
" 0 0 "
" 0 0 "
"  0  "
"  0  "
; W
"0   0"
"0   0"
"0   0"
"0 0 0"
"0 0 0"
"00 00"
"0   0"
; X
"0   0"
"0   0"
" 0 0 "
"  0  "
" 0 0 "
"0   0"
"0   0"
; Y
"0   0"
"0   0"
" 0 0 "
"  0  "
"  0  "
"  0  "
"  0  "
; Z
"00000"
"    0"
"   0 "
"  0  "
" 0   "
"0    "
"00000"
; [
" 000 "
" 0   "
" 0   "
" 0   "
" 0   "
" 0   "
" 000 " 
; \
"0   0"
" 0 0 "
"00000"
"  0  "
"00000"
"  0  "
"  0  " 
; ]
" 000 "
"   0 "
"   0 "
"   0 "
"   0 "
"   0 "
" 000 " 
; ^
"  0  "
" 0 0 "
"0   0"
"     "
"     "
"     "
"     " 
; _
"     "
"     "
"     "
"     "
"     "
"     "
"00000"
;
EOF
0 "
"   0 "
"   0 "
"   0 "
"   0 "
" 000 " 
; ^
"  0  "
" 0 0 "
"0   0"
"     "
"     "
"     "
"     " 
; _
"  VRAM::	DEFW	VRAM1
DRVRAM::	DEFW	VRAM2
;
DSPCHI:	LD	B,127
	LD	C,0
	CALL	DRADR
	LD	DE,(DRVRAM)
	ADD	HL,DE
	CALL	SUBADR
	LD	B,25
	LD	A,(BACKP1)
	LD	E,A
	LD	A,(CHIPAT)
	LD	D,A
DCH100:	LD	A,(IY+0)
	CP	7FH
	CALL	Z,DCHS1
	CALL	NZ,DCHS2
	AND	33H
	LD	(HL),A
	LD	A,(IY+64)
	CP	7FH
	CALL	Z,DCHS1
	CALL	NZ,DCHS2
	AND	0CCH
	OR	(HL)
	LD	(HL),A
	PUSH	DE
	LD	DE,120
	ADD	HL,DE
	LD	DE,64*2
	ADD	IY,DE
	POP	DE
	DJNZ	DCH100
	RET
;
DCHS1:	LD	A,D
	RET
DCHS2:	LD	A,E
RETURN:	RET
;
DSPCHR:	LD	IX,XTBL
DCR10:	LD	A,(IX+IDCODE)
	CP	0FFH
	JR	Z,DCR50
	LD	E,A
	LD	D,0
	LD	HL,DCRCLT
	ADD	HL,DE
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	EX	DE,HL
	LD	DE,HSTEP
	ADD	IX,DE
	LD	DE,DCR20
	PUSH	DE
	JP	(HL)
DCR20:	LD	DE,STEP-HSTEP
	ADD	IX,DE
	JR	DCR10
;
DCR50:	LD	IX,XTBL	
DCR100:	LD	A,(IX+IDCODE)	
	CP	0FFH	
	RET	Z	
	OR	A
	JR	Z,DCR900
	LD	A,(IX+KILLF)
	OR	A
	JR	NZ,DCR900
	LD	A,(IX+IDCODE)
	LD	E,A	
	LD	D,0	
	LD	HL,DCRDST
	ADD	HL,DE	
	LD	E,(HL)	
	INC	HL	
	LD	D,(HL)	
	EX	DE,HL	
	LD	DE,DCR900	
	PUSH	DE	
	JP	(HL)	
DCR900:			
	LD	DE,STEP	
	ADD	IX,DE	
	JR	DCR100	
DCRCLT:
	DEFW	RETURN
	DEFW	SHIPCL
	DEFW	MSLCL
	DEFW	KIRCL
	DEFW	BASECL
	DEFW	INTCL
	DEFW	DSTCL
	DEFW	CRSCL
	DEFW	BTLCL
	DEFW	SMOKCL
	DEFW	BOOMCL
	DEFW	WMSLCL
DCRDST:
	DEFW	RETURN	
	DEFW	SHIPDS	
	DEFW	MSLDS	
	DEFW	KIRDS	
	DEFW	BASEDS	
	DEFW	INTDS
	DEFW	DSTDS	
	DEFW	CRSDS	
	DEFW	BTLDS	
	DEFW	SMOKDS	
	DEFW	BOOMDS	
	DEFW	WMSLDS
;
SHIPDS:	LD	A,(IX+REPCON)
	CPL
	LD	(IX+REPCON),A
	CALL	SETSH	
	CALL	